services:
  aphrodite-engine:
    build:
      context: .
    restart: on-failure:5
    environment:
      - NUM_GPUS=1
      - MODEL_NAME=mistralai/Mistral-7B-v0.1
      - HUGGING_FACE_HUB_TOKEN=
      - QUANTIZATION=
      - DATATYPE=auto
    volumes:
      - ${HOME}/.cache:/root/.cache/
    shm_size: 1g
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]